import { PageHeader } from '@/components/admin/page-header'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

const selectedModules = ['admin-shell', 'user-management', 'role-permission-management', 'project-management', 'project-repository-management', 'kanban-management', 'ticket-management']

export function DashboardPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Overview"
        title="Assembly dashboard"
        description="This dashboard reflects the selected module assembly for the generated application skeleton."
      />

      <Card className="bg-card/95">
        <CardHeader>
          <CardTitle className="text-lg">Selected modules</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap gap-2">
        <Badge key="user-management" variant="outline" className="rounded-full">
          user-management
        </Badge>
        <Badge key="role-permission-management" variant="outline" className="rounded-full">
          role-permission-management
        </Badge>
        <Badge key="project-management" variant="outline" className="rounded-full">
          project-management
        </Badge>
        <Badge key="project-repository-management" variant="outline" className="rounded-full">
          project-repository-management
        </Badge>
        <Badge key="kanban-management" variant="outline" className="rounded-full">
          kanban-management
        </Badge>
        <Badge key="ticket-management" variant="outline" className="rounded-full">
          ticket-management
        </Badge>
          </div>
          <p className="text-sm leading-6 text-muted-foreground">
            Generated by the Java-compatible app assembly implementation for {selectedModules.length} modules.
            Keep route wiring, SQL contracts, and this selected module list aligned with app-manifest.json.
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
